name: Test Cron Trigger

on:
  schedule:
    - cron: '* * * * *'  # Каждую минуту
  workflow_dispatch:  # Позволяет запуск вручную

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print current date
