name: Daily Telegram Bot

on:
  schedule:
    - cron: '0 7 * * *'  # Запуск каждый день в 07:00 UTC (10:00 МСК)
  workflow_dispatch:  # Позволяет вручную запустить workflow

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск бота
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py
